version: "3.5"

services:
  diun:
    image: zalgar/xrit-rx-docker:latest
    container_name: xrit-rx-docker
    volumes:
      - "./xrit-rx.ini:/xrit-rx/xrit-rx.ini" #path to config ini
      - "./received:/xrit-rx/received" #path to received images
    ports:
      - "1692:1692"
    restart: unless-stopped
