name: Build and Release

on: 
  push:
    branches: [ master ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_release:
    name: Build Release Package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Set up Node.js (for Sass)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Sass
        run: npm install -g sass
        
      - name: Create release directory structure
        run: |
          mkdir -p release
          
      - name: Copy all src files
        run: |
          cp -r src/* release/
          echo "=== Verifying src copy completed ==="
          ls -la release/
          echo "=== Checking if tools directory exists ==="
          ls -la release/tools/ || echo "Tools directory not found!"
          
      - name: Compile Sass to CSS (overwrite copied SCSS)
        run: |
          sass --no-source-map release/html/css/dash.scss:release/html/css/dash.css
          
      - name: Verify CSS compilation
        run: |
          echo "=== Checking CSS files ==="
          ls -la release/html/css/
          echo "=== CSS file content preview ==="
          head -30 release/html/css/dash.css
          echo "=== Checking for progress styles ==="
          grep -A 5 -B 5 "progress" release/html/css/dash.css || echo "No progress styles found"
          
      - name: Clean up development files
        run: |
          find release -name "__pycache__" -type d -exec rm -rf {} + || true
          find release -name "*.pyc" -delete || true
          find release -name ".DS_Store" -delete || true
          find release -name "received" -type d -exec rm -rf {} + || true
          rm -f release/html/css/*.scss || true
          
      - name: Verify tools directory contents
        run: |
          echo "=== Checking tools directory contents ==="
          ls -la release/tools/
          echo "=== Checking for timelapse scripts ==="
          ls -la release/tools/timelapse* || echo "No timelapse scripts found"
          echo "=== Full release directory structure ==="
          find release -type f | head -20
          
      - name: Copy config and requirements
        run: |
          cp src/*.ini release/ || true
          cp requirements.txt release/
          
      - name: Set executable permissions for scripts
        run: |
          chmod +x release/tools/*.py || true
          chmod +x release/tools/*.sh || true
          echo "=== Verifying script permissions ==="
          ls -la release/tools/timelapse* || echo "No timelapse scripts found"
          
      - name: Create zip archive
        run: |
          cd release
          zip -r ../xrit-rx.zip .
          cd ..
          
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: xrit-rx-release
          path: xrit-rx.zip
          
      - name: Upload to release (if triggered by release)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./xrit-rx.zip
          asset_name: xrit-rx.zip
          asset_content_type: application/zip

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    # Only run Docker build on releases or manual workflow dispatch
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
         
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Determine Docker tags
        id: docker_tags
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tags=zalgar/xrit-rx-docker:latest,zalgar/xrit-rx-docker:${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tags=zalgar/xrit-rx-docker:latest" >> $GITHUB_OUTPUT
          fi
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}
